$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file


properties:

  max_threads:
    type: number

  design:
    type: str


  steps:
    type: object
    properties:
      install:
        type: boolean
      mapping:
        type: boolean
      mapping:
        type: boolean

  reference:
    type: object
    properties:
      build:
        type: str
      release:
        type: str
      species:
        type: str
      fasta:
        type: str